prisma/schema.prisma, src/components/admin/AdminView.tsx, src/components/queue/CreateTicket.tsx, src/components/queue/CreateTicketForm.tsx, src/components/queue/QueueLayout.tsx, src/components/queue/TicketCard.tsx, src/components/queue/TicketList.tsx, src/components/queue/TicketQueue.tsx, src/components/ticket-page/Chat.tsx, src/components/ticket-page/InnerTicket.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/TicketButtons.tsx, src/pages/ticket/[id].tsx, src/server/trpc/router/ticket.ts, src/utils/utils.ts
Implement https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/21 which allows students to create public tickets which can be joined by other students.
=> Implement group tickets

prisma/schema.prisma, src/components/queue/CreateTicketForm.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/server/trpc/router/ticket.ts, src/styles/globals.css
While we still want https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/23, adding a form for student to describe where they are is a good quick workaround.
=> Add form input for location description

src/components/queue/TicketList.tsx
Allows grouping by Assignment and location
=> Field grouping

prisma/schema.prisma, src/components/layout/NamePopoverForm.tsx, src/components/layout/Navbar.tsx, src/components/ticket-page/Chat.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/StaffNotes.tsx, src/pages/api/auth/[...nextauth].ts, src/server/trpc/router/ticket.ts, src/server/trpc/router/user.ts, src/types/next-auth.d.ts
Add a field for a preferred name for users
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/35
=> Preferred name field

prisma/seed.ts, src/components/admin/AdminCard.tsx, src/components/admin/AdminView.tsx, src/components/admin/ImportUsers.tsx, src/components/layout/NamePopoverForm.tsx, src/components/layout/Navbar.tsx, src/components/queue/Broadcast.tsx, src/components/queue/OpenOrCloseQueue.tsx, src/components/queue/TicketCard.tsx, src/components/queue/TicketList.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/pages/_app.tsx, src/styles/globals.css, src/utils/constants.ts, src/utils/utils.ts
Make dark mode color a bit darker and other misc. fixes
=> UI Improvements

package-lock.json, package.json, prisma/schema.prisma, src/components/admin/AdminCard.tsx, src/components/admin/AdminList.tsx, src/components/admin/AdminView.tsx, src/components/admin/ImportUsers.tsx, src/server/trpc/router/admin.ts
Allows admin users to hide locations/assignments. Also includes a refactor of the Admin components so locations and assignments use the same component.
=> Admin hidden

src/components/layout/Layout.tsx, src/pages/admin/index.tsx, src/pages/index.tsx, src/pages/ticket/[id].tsx
Refactor all pages by putting the logic for Ably and session in the layout component. This will enure that any future pages will be connected to Ably and authorized.
=> Put shared logic in Layout

src/components/layout/AvatarDropdown.tsx, src/components/layout/HamburgerMenu.tsx, src/components/layout/Navbar.tsx
=> Hamburger menu

src/components/ticket-page/Countdown.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/server/trpc/router/ticket.ts
Fixes https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/47
The **key** is to force a rerender on the child Counter component, using the _key_ prop.
Also removed useless comments.
=> Fix issue where absent timer didnt reset

prisma/schema.prisma, src/components/activity/ActivityView.tsx, src/components/admin/AdminCard.tsx, src/components/admin/AdminList.tsx, src/components/admin/ImportUsersMethod.tsx, src/components/layout/AvatarDropdown.tsx, src/components/queue/ReceiveBroadcast.tsx, src/components/queue/TicketCard.tsx, src/components/queue/TicketList.tsx, src/components/queue/TicketQueue.tsx, src/components/ticket-page/Chat.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/StaffNotes.tsx, src/components/ticket-page/TicketButtons.tsx, src/components/ticket-page/TicketView.tsx, src/pages/ticket/[id].tsx, src/server/trpc/router/admin.ts, src/server/trpc/router/ticket.ts, src/server/trpc/trpc.ts
This allows you to set certain assignments (ie: Setup) as priority and introduces a role for Interns. Interns have the ability to help/resolve tickets but can't open/close the queue or broadcast messages. They also have an "Escalate" option when they're helping someone which marks the ticket as priority.
=> Priority tickets and AI role

src/components/queue/TicketQueue.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/75
=> Priority default

src/components/ticket-page/TicketButtons.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/74
=> Fix button layout

src/utils/hooks/useNotification.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/86
=> Add sound to notification

src/components/queue/TicketCard.tsx, src/components/queue/TicketList.tsx, src/components/queue/TicketQueue.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/73
=> Add timer to absent && fix absent bug

src/components/queue/TicketQueue.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/94
=> Remove priority tickets when they're assigned

prisma/schema.prisma, src/components/modals/ConfirmPublicToggleModal.tsx, src/components/queue/CreateTicketForm.tsx, src/components/queue/TicketCard.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/server/trpc/router/ticket.ts, src/utils/constants.ts
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/92
=> Form refactor

src/components/queue/TicketQueue.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/TicketButtons.tsx, src/server/trpc/router/ticket.ts
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/90
=> Make public/private button

src/components/queue/TicketCard.tsx, src/components/queue/TicketQueue.tsx
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/101
=> Change ticket index to be number on queue

src/components/layout/Navbar.tsx, src/components/queue/CreateTicketForm.tsx, src/components/queue/TicketCard.tsx, src/utils/utils.ts
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/79
=> Add redirect from personal queue

src/components/ticket-page/InnerTicketInfo.tsx
Changes the max for editing a description to 1000
=> Edit desc fix

src/components/queue/QueueLayout.tsx, src/components/queue/TicketCard.tsx, src/components/queue/TicketQueue.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/TicketButtons.tsx, src/server/trpc/router/ticket.ts
Allows for staff members to create tickets (useful for public tickets)
Also makes it so names are visible during the pending stage
=> Staff ticket

src/components/queue/TicketCard.tsx, src/components/ticket-page/TicketButtons.tsx
Automatically requeues a ticket when it is escalated
=> Requeue on escalate

src/components/modals/PublicTicketsExistModal.tsx, src/components/queue/TicketQueue.tsx
There is now a modal that appears whenever a student opens the page and there are public tickets. Hopefully this will encourage more people to join public tickets.
=> Add modal for public tickets

.gitignore, src/components/activity/ActivityView.tsx, src/components/activity/GlobalLog.tsx, src/components/activity/PersonalLog.tsx, src/components/activity/StatsView.tsx, src/pages/activity/global.tsx, src/pages/activity/index.tsx, src/server/trpc/router/ticket.ts
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/76
=> Global activity

src/components/activity/StatsView.tsx, src/server/trpc/router/stats.ts
I have no idea if this is the best way to do it, but I think it works...
This seems like it's the more correct way to do it, but I couldn't get it to work :( https://trpc.io/docs/reactjs/useinfinitequery#getinfinitedata
=> Stats loading

src/components/activity/StatsView.tsx
=> Stats view select start date

src/components/queue/CreateTicketForm.tsx
Changed Vercel to deploy from this repo so I'm testing it out
=> Small change to force redeploy

prisma/schema.prisma, src/components/admin/AdminView.tsx, src/components/admin/CooldownTimer.tsx, src/components/queue/CreateTicketForm.tsx, src/server/trpc/router/admin.ts, src/server/trpc/router/ticket.ts
https://github.com/Berkeley-CS61B/simple-office-hours-queue/issues/119
=> Add cooldown timer

src/components/admin/CooldownTimer.tsx, src/components/queue/CreateTicket.tsx, src/components/queue/CreateTicketForm.tsx, src/components/queue/QueueLayout.tsx, src/server/trpc/router/ticket.ts
Students didn't have a way of knowing how much time they have left before they can make a new ticket. This adds a countdown.
=> Add timer for students on cooldown

src/components/queue/TicketCard.tsx, src/components/queue/TicketList.tsx, src/components/ticket-page/InnerTicketInfo.tsx, src/components/ticket-page/TicketButtons.tsx, src/server/trpc/router/ticket.ts
for location/assignment-specific closing
=> adding close all tickets button

src/components/admin/AdminList.tsx, src/components/queue/TicketList.tsx, src/server/trpc/router/admin.ts
categories are mandatory for assignments.
categories are not mandatory for locations. if no category filters are selected for a location, any assignment can be requested in that location.
assignment and location names must be unique
#150
=> admin page improvements

prisma/schema.prisma, src/components/admin/AdminList.tsx, src/components/layout/AvatarDropdown.tsx, src/components/modals/EditTemplateModal.tsx, src/components/queue/CreateTicketForm.tsx, src/components/ticket-page/InnerTicketInfo.tsx
make student support link not visible to students.
=> fix student support link visibility
